# --- Build perf ---
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# --- Fabric / Loom ---
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.16.0-alpha.15

# --- Mod ---
mod_version=1.4.3
maven_group=com.pedalhat.lategameplus
archives_base_name=lategameplus

# --- Deps ---
fabric_version=0.144.3+26.1
modmenu_version=18.0.0-alpha.8
yacl_version=3.9.1+26.1-fabric
jei_version=29.2.0.17
